const CHAT_STATES = {
  INIT: "INIT",
  GREETING: "GREETING",
  INTEREST_CHECK: "INTEREST_CHECK",
  QUALIFICATION: "QUALIFICATION",
  PRODUCT_PITCH: "PRODUCT_PITCH",
  CTA: "CTA",
  COMPLETED: "COMPLETED"
};

module.exports = CHAT_STATES;
